variable "vpc" {}
variable "tags" {}
variable "env" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_route_table_id" {}
variable "alb" {}
variable "docdb" {}
variable "rds" {}
variable "elasticache" {}
variable "rabbitmq" {}
variable "ami_id" {}
variable "ssh_ingress_cidr" {}
variable "hosted_zone_id" {}
variable "app" {}